name: code_route_flutter
description: Application d'apprentissage du code de la route
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.3.5
  syncfusion_flutter_pdfviewer: ^33.2.3
  syncfusion_flutter_pdf: ^33.2.3
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  image_picker: ^1.2.1
  flutter_tts: ^4.2.5
  printing: ^5.14.3
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  pdf: ^3.12.0
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0
  firebase_storage: ^13.4.1
  file_picker: ^8.0.0
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  confetti: ^0.8.0
  camera: ^0.10.5+9
  google_mlkit_object_detection: ^0.11.0
  google_mlkit_text_recognition: ^0.11.0
  tflite_flutter: ^0.10.0
  google_generative_ai: ^0.4.3
  hive: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "transparent"
  adaptive_icon_foreground: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#0F172A"
    theme_color: "#0F172A"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/questions/
    - assets/cours/
