// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWwnwcafME4RstNx5q-4Y3gmHlO0QuKfQ',
    appId: '1:570731313335:web:95b9712fca974f574e3532',
    messagingSenderId: '570731313335',
    projectId: 'coderoute-8eeb0',
    authDomain: 'coderoute-8eeb0.firebaseapp.com',
    storageBucket: 'coderoute-8eeb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7cOBUEHVj0z0JLPwghnLACU7V27A38M',
    appId: '1:570731313335:android:050878437c979e454e3532',
    messagingSenderId: '570731313335',
    projectId: 'coderoute-8eeb0',
    storageBucket: 'coderoute-8eeb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1A-Zr7OLMBaWGcXJY_R2M6K3rDhcvszA',
    appId: '1:570731313335:ios:e50edd663d323e324e3532',
    messagingSenderId: '570731313335',
    projectId: 'coderoute-8eeb0',
    storageBucket: 'coderoute-8eeb0.firebasestorage.app',
    iosBundleId: 'com.example.codeRouteFlutter',
  );
}
